// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyusbfotwfpxenhktxne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5dXNiZm90d2ZweGVuaGt0eG5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjUwNzcsImV4cCI6MjA3MzM0MTA3N30.Q2fGnLTrhhRFuhLvS6zm6MF0gQVqWmEH4LLH50GOJRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});